### PR TITLE
Feature: overlays

### PR DESCRIPTION
**Pull request by sharnik**

### CODE REVIEW

**Comment by mpasternacki** [comment]
The refactor is nice, and the feature's implementation looks solid. However, the idea is for overlay's modules to be merged on top of each other into single directory – updated feature file to reflect that. This shouldn't require too big changes, though.

I've also added a small feature: ability to specify overlay's path, to avoid conflicts if one wants to have e.g. an `overlay "/"` and `overlay "/merged"` in the same repo (and for possibility of using descriptive names).

Please also update the README file.

**Comment by sharnik** [comment]
Check out how cool it is now!

**Comment by mpasternacki** [comment]
Cool! Works as advertised.

I've found two issues that I went forward and solved to get a feeling of the refactored codebase (I have to admit I'm impressed with the current "segmented" architecture). Please sanity check the updates and merge if they're fine.

There will probably be some rough edges to clean up, such as interactions of overlays with `vendor list`, `vendor log`, `vendor diff`, etc - it will be better to take care of that after the merge, when overlays see some real usage. Before 1.0 we'll need to do a proper manual QA run of the features anyway, so expect issues then.

If you're up to that, please add overlays to README (in develop); otherwise, I'll pick that up in the following week.

**Comment by sharnik** [comment]
Changes seem okay except for the breaking test. I was wondering if we run the Vendor::Tool conjure! in the main application directory instead of a temporary (and it would be difficult to run in the temporary) maybe we should run there the super part as well? It'd need to be reflecte in the docs, I think.

**Pull request merged**
