### PR TITLE
Allow missing Vendorfile

### PR DESCRIPTION
**Pull request by sharnik**
The idea is to allow initialization when the vendorfile's missing. That would mean that all the commands that operate on modules will fail (as no modules get recognized).

If we don't find a Vendorfile, we display a warning to let the user know something might be wrong.

### CODE REVIEW

**Comment by mpasternacki** [comment]
I like this approach, but it still needs polishing:
- [x] Warning message copy is not clear. Something along the lines of "Vendorificator needs to run in the directory containing Vendorfile or config/vendor.rb" will give user an idea of what they're supposed to do. In a perfect situation, the warning would be displayed only when Vendorfile is actually needed. 
- [x] Add a Cucumber feature
- [x] Make sure that there are no confusing messages (or even worse, silence on the wire) when commands that need Vendorfile run without one; add features for it
- [x] Edge case to handle gracefully: empty Vendorfile

**Comment by sharnik** [comment]
What do you mean by handling gracefully an empty Vendorfile? I think it seems to be pretty good now: no warning and no blow ups (at least I haven't experienced any).

**Comment by mpasternacki** [comment]
By "handling empty Vendorfile" I mean just making sure we won't blow up (a feature specing the desired behaviour would be nice). I'm not sure whether we should display warning on empty Vendorfile, but let's just keep it as it is (don't display warning, and don't blow up), and maybe update later it if there are any complains or other good reason. 

I just wasn't sure what is the current behaviour, so I added it to the checklist.

**Comment by sharnik** [comment]
Looks like on Travis server the output of "vendor help" is more like "rake -T". It even says "rake" in it. 
@mpasternacki - do you have any idea why that might be?

**Pull request merged**
